### ISSUE TITLE
Incompatible with microprofile-health-api 3?

### ISSUE THREAD

**Issue by garyhodgson** [microprofile-extensions/health-ext#10]
Hi, Just a FYI, I just updated to quarkus 2.0.0.Final, which I believe has microprofile-health-api 3, and it appears that healthprobe-jvm 1.1.0 is no longer compatible?

```
2021-06-30 22:30:37,468 ERROR [io.sma.health] (vert.x-worker-thread-0) SRHCK01000: Error processing Health Checks: java.lang.NoSuchMethodError: org.eclipse.microprofile.health.HealthCheckResponseBuilder.state(Z)Lorg/eclipse/microprofile/health/HealthCheckResponseBuilder;
  at org.microprofileext.health.jvm.HeapMemoryHealthCheck.call(HeapMemoryHealthCheck.java:37)
  at org.microprofileext.health.jvm.HeapMemoryHealthCheck_Subclass.call$$superforward1(HeapMemoryHealthCheck_Subclass.zig:89)
  at org.microprofileext.health.jvm.HeapMemoryHealthCheck_Subclass$$function$$1.apply(HeapMemoryHealthCheck_Subclass$$function$$1.zig:24)
  at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
  at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.proceed(InvocationInterceptor.java:62)
  at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.monitor(InvocationInterceptor.java:49)
  at io.quarkus.arc.runtime.devconsole.InvocationInterceptor_Bean.intercept(InvocationInterceptor_Bean.zig:521)
  at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
  at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
  at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
  at org.microprofileext.health.jvm.HeapMemoryHealthCheck_Subclass.call(HeapMemoryHealthCheck_Subclass.zig:145)
  at org.microprofileext.health.jvm.HeapMemoryHealthCheck_ClientProxy.call(HeapMemoryHealthCheck_ClientProxy.zig:155)
  at io.smallrye.context.impl.wrappers.SlowContextualSupplier.get(SlowContextualSupplier.java:21)
  at io.smallrye.mutiny.operators.uni.builders.UniCreateFromItemSupplier.subscribe(UniCreateFromItemSupplier.java:28)
  at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
  at io.smallrye.mutiny.operators.uni.UniOnFailureFlatMap.subscribe(UniOnFailureFlatMap.java:31)
  at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
  at io.smallrye.mutiny.operators.uni.UniOnItemTransform.subscribe(UniOnItemTransform.java:22)
  at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
  at io.smallrye.mutiny.operators.uni.UniAndCombination$UniHandler.subscribe(UniAndCombination.java:203)
  at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
  at io.smallrye.mutiny.operators.uni.UniAndCombination$AndSupervisor.run(UniAndCombination.java:71)
  at io.smallrye.mutiny.operators.uni.UniAndCombination$AndSupervisor.access$000(UniAndCombination.java:53)
  at io.smallrye.mutiny.operators.uni.UniAndCombination.subscribe(UniAndCombination.java:50)
  at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
  at io.smallrye.mutiny.operators.uni.UniBlockingAwait.await(UniBlockingAwait.java:54)
  at io.smallrye.mutiny.groups.UniAwait.atMost(UniAwait.java:61)
  at io.smallrye.health.SmallRyeHealthReporter.getHealth(SmallRyeHealthReporter.java:179)
  at io.smallrye.health.SmallRyeHealthReporter_Subclass.getHealth$$superforward1(SmallRyeHealthReporter_Subclass.zig:1046)
  at io.smallrye.health.SmallRyeHealthReporter_Subclass$$function$$4.apply(SmallRyeHealthReporter_Subclass$$function$$4.zig:24)
  at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
  at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.proceed(InvocationInterceptor.java:62)
  at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.monitor(InvocationInterceptor.java:49)
  at io.quarkus.arc.runtime.devconsole.InvocationInterceptor_Bean.intercept(InvocationInterceptor_Bean.zig:521)
  at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
  at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
  at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
  at io.smallrye.health.SmallRyeHealthReporter_Subclass.getHealth(SmallRyeHealthReporter_Subclass.zig:1843)
  at io.smallrye.health.SmallRyeHealthReporter_ClientProxy.getHealth(SmallRyeHealthReporter_ClientProxy.zig:754)
  at io.quarkus.smallrye.health.runtime.SmallRyeHealthHandler.getHealth(SmallRyeHealthHandler.java:11)
  at io.quarkus.smallrye.health.runtime.SmallRyeHealthHandlerBase.doHandle(SmallRyeHealthHandlerBase.java:44)
  at io.quarkus.smallrye.health.runtime.SmallRyeHealthHandlerBase.handle(SmallRyeHealthHandlerBase.java:31)
  at io.quarkus.smallrye.health.runtime.SmallRyeHealthHandler.handle(SmallRyeHealthHandler.java:7)
  at io.quarkus.smallrye.health.runtime.SmallRyeHealthHandlerBase.handle(SmallRyeHealthHandlerBase.java:19)
  at io.vertx.ext.web.impl.BlockingHandlerDecorator.lambda$handle$0(BlockingHandlerDecorator.java:48)
  at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:160)
  at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:96)
  at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:158)
  at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
  at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2442)
  at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1476)
  at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
  at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
  at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
  at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by phillip-kruger** [comment]
Good catch, yes this would need an update. You are welcome to provide a PR ?

**Comment by phillip-kruger** [comment]
@garyhodgson  - Release for 1.2.0 done. Should be in maven central in a few mins. Thanks :)
